"""Native NVRTC compilation and TileLang adapter compatibility fixes."""

from __future__ import annotations

import functools
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from collections.abc import Callable

    # cuda.bindings.driver is a Cython extension without a Python stub.
    from cuda.bindings import driver  # pyrefly: ignore[missing-module-attribute]
    from tilelang.jit.adapter.nvrtc.adapter import NVRTCKernelAdapter
    from tilelang.jit.adapter.nvrtc.libgen import NVRTCLibraryGenerator
    from tilelang.jit.kernel import JITKernel
    from tilelang.language.eager import PrimFunc


def compile[**P, R](
    function: PrimFunc[P, R],
    pass_configs: dict[str, object] | None = None,
    compile_flags: list[str] | None = None,
) -> JITKernel[P, R]:
    """Use NVRTC and explicit launch arguments for an already selected config."""
    from tilelang.jit import compile

    return compile(
        function,
        out_idx=[],
        execution_backend="nvrtc",
        pass_configs=pass_configs,
        compile_flags=compile_flags,
    )


def install() -> None:
    """Install compatibility fixes required by the current TileLang release."""
    _restore_cached_libpath()
    _restore_single_argument_tuple()
    _rewrite_nvrtc_temporary_alias()


def _restore_cached_libpath() -> None:
    """Restore cached NVRTC libpath until TileLang includes upstream PR #3193."""
    from tilelang.jit.adapter.nvrtc.adapter import NVRTCKernelAdapter

    original = NVRTCKernelAdapter.from_database.__func__
    if getattr(original, "_restores_cached_libpath", False):
        return

    @functools.wraps(original)
    def from_database(
        cls: type[NVRTCKernelAdapter], *args: object, **kwargs: object
    ) -> NVRTCKernelAdapter:
        adapter = original(cls, *args, **kwargs)
        if not hasattr(adapter, "libpath"):
            adapter.libpath = adapter.lib_generator.libpath
        return adapter

    vars(from_database)["_restores_cached_libpath"] = True
    NVRTCKernelAdapter.from_database = cast(
        "Callable[..., NVRTCKernelAdapter]", classmethod(from_database)
    )


def _restore_single_argument_tuple() -> None:
    """Normalize the one-argument launch tuple emitted by TileLang 0.1.14."""
    from tilelang.jit.adapter.nvrtc.libgen import NVRTCLibraryGenerator

    original = NVRTCLibraryGenerator.load_lib
    if getattr(original, "_restores_argument_tuple", False):
        return

    @functools.wraps(original)
    def load_lib(self: NVRTCLibraryGenerator, lib_path: str | None = None) -> None:
        original(self, lib_path)
        # This callable belongs to a Python module generated by TileLang.
        launch: Callable[
            [driver.CUlaunchConfig, driver.CUfunction, tuple[object, object], object],
            tuple[driver.CUresult],
        ] = vars(self.pymodule)["cuLaunchKernelEx"]

        @functools.wraps(launch)
        def launch_kernel(
            config: driver.CUlaunchConfig,
            kernel: driver.CUfunction,
            parameters: tuple[object, object],
            extra: object,
        ) -> tuple[driver.CUresult]:
            values, types = parameters
            if not isinstance(values, tuple):
                parameters = ((values,), (types,))
            return launch(config, kernel, parameters, extra)

        vars(self.pymodule)["cuLaunchKernelEx"] = launch_kernel

    vars(load_lib)["_restores_argument_tuple"] = True
    NVRTCLibraryGenerator.load_lib = load_lib


def _rewrite_nvrtc_temporary_alias() -> None:
    """Replace an aliasing expression rejected by CUDA 13.3 NVRTC."""
    from tilelang.jit.adapter.nvrtc.libgen import NVRTCLibraryGenerator

    original = NVRTCLibraryGenerator.compile_lib
    if getattr(original, "_rewrites_temporary_alias", False):
        return

    @functools.wraps(original)
    def compile_lib(self: NVRTCLibraryGenerator, timeout: float | None = None) -> None:
        invalid = "*(unsigned long long*)&make_float2("
        assert self.lib_code is not None
        if invalid in self.lib_code:
            helper = """
__device__ inline unsigned long long _tl_pack_float2(float first, float second) {
  return static_cast<unsigned long long>(__float_as_uint(first)) |
         (static_cast<unsigned long long>(__float_as_uint(second)) << 32);
}
"""
            self.lib_code = self.lib_code.replace(
                'extern "C"', helper + '\nextern "C"', 1
            ).replace(invalid, "_tl_pack_float2(")
        original(self, timeout)

    vars(compile_lib)["_rewrites_temporary_alias"] = True
    NVRTCLibraryGenerator.compile_lib = compile_lib
